### ISSUE TITLE
calls to missing resources

### ISSUE THREAD

**Issue by fafayqa** [macroing/Dayflower#2] opened 2022-03-07 11:28 UTC
Throughout the code there is zillions of calls to NONEXISTENT RESOURCES, that is no such directories/files are nowhere to be found in the code package downloadable from here at all!

Some exmaples of such calls:

```
private static final double[] IMAGE_4_D_DISPLACEMENT_MAP = Image.image4DLoad("./resources/textures/bricks2_disp.jpg");
private static final double[] IMAGE_4_D_NORMAL_MAP = Image.image4DLoad("./resources/textures/bricks2_normal.jpg");
```

There is no folder "textures" in resources folder or anywhere else in the whole package, and I would like to point out this is even in the test classes that should serve as presentation/preview of supposed functionalities of Dayflower!

Or this one here:

```
public static void main(final String[] args) {
        doRender("./generated/Simplex/Cone.png", 270.0D, cone3D(), 4.0D);
        doRender("./generated/Simplex/Cylinder.png", 270.0D, cylinder3D(), 4.0D);
        doRender("./generated/Simplex/Disk.png", 0.0D, disk3D(), 2.0D);
        doRender("./generated/Simplex/Hyperboloid.png", 270.0D, hyperboloid3D(), 4.0D);
        doRender("./generated/Simplex/Paraboloid.png", 270.0D, paraboloid3D(), 4.0D);
        doRender("./generated/Simplex/Plane.png", 0.0D, plane3D(point3D(0.0D, -1.0D, 0.0D), point3D(0.0D, -1.0D, 1.0D), point3D(1.0D, -1.0D, 0.0D)), 0.1D);
        doRender("./generated/Simplex/Polygon.png", 0.0D, polygon3D(), 2.0D);
        doRender("./generated/Simplex/Rectangle.png", 0.0D, rectangle3D(), 2.0D);
        doRender("./generated/Simplex/RectangularCuboid.png", 0.0D, rectangularCuboid3D(), 2.0D);
        doRender("./generated/Simplex/Sphere.png", 270.0D, sphere3D(), 4.0D);
        doRender("./generated/Simplex/Torus.png", 0.0D, torus3D(), 2.0D);
        doRender("./generated/Simplex/Triangle.png", 0.0D, triangle3D(), 4.0D);
    }
```

There is no folder called "generated" anywhere in the whole package, and I would like to point out this is even in the test classes that should serve as presentation/preview of supposed functionalities of Dayflower!

Thus there is no chance to even test this!

**Comment by macroing** [comment] 2022-03-07 17:15
The code that you are referring to in this issue, relates to an unstable API called Simplex API. It is not used by any other parts of Dayflower and needs a lot of refactoring. In the future it should not refer to any resources.

Some folders, like resources/models and resources/textures, used to be part of the repository. They were removed because of potential copyright issues.

The generated folder (including its subfolders and files) should not exist by default. The files and folders are generated by various manual tests (not unit tests).

The src/test/java folder currently contains unit tests and other manual tests. The manual tests are not intended for general use. Most of them will be removed in the future. Many of them refer to files that do not exist in the repository.

**Comment by fafayqa** [comment] 2022-03-08 09:44
Could you, PLEASE< provide ANY really functional example package so I can wrap my head around it? You see: this reminds me of a one very old but still great renderer called SunFlow that several yrs ago I highly modified for my own purposes, but it simply lacks the GPU acceleration part, thus my renders take like 2+ hrs to render in FullHD. If I understand how this Dayflower renderer works I am thinking of rpelacing my old SunFlow version with this one but I still doe snot even was able top test to render anything cos all I get is this:
![Image 001](https://user-images.githubusercontent.com/26612946/157210825-71e6ee19-bbf8-47b2-885e-9c90863b0962.png)

**Comment by macroing** [comment] 2022-03-08 12:44
When you run the application, you can open one of the .java files from resources/scenes using File > Open > CPU Renderer or File > Open > GPU Renderer. This assumes that an implementation of the Java Compiler API is present on your class-path. In Java 8 or earlier, this implementation was provided in tools.jar.

The reason the plane is not showing in the top image, might be because you're trying to add primitives dynamically while running the GPU renderer. The GPU renderer does not have support for dynamic scenes yet. This is a feature that is worked on, but will take a while to finish.

The Cornell Box scene is using a point light as light source. This is because the GPU renderer does not have support for explicit area lights yet. The "bad" look might be because the example is only rendering once per pixel (a render pass). The render() method has an overloaded method render(int). The int parameter represents the number of passes to render.

I assume the test with the example GPU renderer fails because Aparapi was not on the class-path. Aparapi is responsible for decompiling the Java bytecode into OpenCL C99 and execute it on the GPU.

**Comment by macroing** [comment] 2022-03-08 18:03
The image with the ClearCoatMaterial scene you posted above looks like that for me when I remove aparapi_x86_64.dll. Aparapi also writes a message to standard output. When the GPU renderer fails, it falls back to a CPU renderer using a Java thread pool (JTP). However, I havn't had time to fix the JTP version, which needs some changes to work. Hence the weird artifacts.

It might be that you require a 32-bit version of the .dll file. I havn't been able to compile any other version though. Does your GPU have support for double-precision?

Dayflower only has one native file, the one for Aparapi. But Aparapi has other versions for different operating systems and architectures.

The application is rendering one pass at a time, until you stop it by closing the tab.

One thing that might be good to know. If you get the GPU renderer to work, the first time it compiles will take a while. Maybe a minute or so.

**Comment by fafayqa** [comment] 2022-03-09 09:21
In fact, I used the dll you provided in the zip file. I will try to download the original actual Aparapi, change it and will let you know if that was the case. 
Also, there should definitely be a option to set definitive number of passes and not passing constantly till the app/tab is closed. Just add a int as parameter as you did with the render and samples number.

**Comment by macroing** [comment] 2022-03-09 17:00
A couple of years ago someone forked Aparapi and created a website for it. The version you're referring to is for that fork. 

Dayflower is using a fork of the original version that includes a bug fix and some new functions.

The bug fix is necessary and Dayflower would not work without it. The problem is that functions in OpenCL C99 have to be declared or implemented at a location in the source code that comes before any calls to these functions. It was fixed by adding declarations for these functions before their implementations. I could not find this fix in the latest version of Aparapi.

I did contribute some of the functions to the forked version of Aparapi, though. But that was before the bug fix.

My version of Aparapi does not have any native source code changes. So maybe you could try the .dll file found in this repository (the original Aparapi): https://github.com/aparapi/aparapi

**Comment by macroing** [comment] 2022-03-21 17:27
Aparapi native files for Linux, Mac and the 32-bit version of Windows have been added. They have not been tested yet, though.

**Closed** 2022-03-26 09:03 UTC
